=== camenduru/onevision-flux.1-dev/schema.json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#",
  "type": "object",
  "properties": {
    "readme": {
      "type": "string",
      "title": "LLaVA-OneVision: Easy Visual Task Transfer",
      "author": "Bo Li, Yuanhan Zhang, Dong Guo, Renrui Zhang, Feng Li, Hao Zhang, Kaichen Zhang, Yanwei Li, Ziwei Liu, Chunyuan Li",
      "page": "https://llava-vl.github.io/blog/2024-08-05-llava-onevision/",
      "paper": "https://arxiv.org/abs/2408.03326",
      "code": "https://github.com/LLaVA-VL/LLaVA-NeXT",
      "jupyter": "https://github.com/camenduru/LLaVA-OneVision-jupyter",
      "api": "https://github.com/camenduru/tost-api-examples/blob/main/v1/onevision-flux.1-dev.ipynb",
      "tags": [
        "Vision to Image"
      ],
      "widget": "readme"
    },
    "input_image_check": {
      "type": "string",
      "description": "Input Image URL",
      "widget": "textarea"
    },
    "final_width": {
      "type": "integer",
      "description": "Final Width"
    },
    "tag_prompt": {
      "type": "string",
      "description": "Tag Prompt",
      "widget": "textarea"
    },
    "additional_prompt": {
      "type": "string",
      "description": "Additional Prompt",
      "widget": "textarea"
    },
    "tag_seed": {
      "type": "integer",
      "description": "Tag Seed (if 0 random)"
    },
    "tag_temp": {
      "type": "number",
      "description": "Tag Temp"
    },
    "tag_max_tokens": {
      "type": "integer",
      "description": "Tag Max Tokens",
      "widget": "textarea"
    },
    "seed": {
      "type": "integer",
      "description": "Seed (if 0 random)"
    },
    "steps": {
      "type": "integer",
      "widget": "select",
      "description": "Steps",
      "oneOf": [
        {
          "description": "10",
          "enum": [
            10
          ]
        },
        {
          "description": "20",
          "enum": [
            20
          ]
        },
        {
          "description": "30",
          "enum": [
            30
          ]
        }
      ],
      "default": 20
    },
    "guidance": {
      "type": "number",
      "description": "Guidance"
    },
    "lora_file": {
      "type": "string",
      "widget": "select",
      "description": "Lora File",
      "oneOf": [
        {
          "description": "Advokat Aesthetic",
          "enum": [
            "advokat_aesthetic10k.safetensors"
          ]
        },
        {
          "description": "XLabs Anime",
          "enum": [
            "xlabs_anime.safetensors"
          ]
        },
        {
          "description": "XLabs Art",
          "enum": [
            "xlabs_art.safetensors"
          ]
        },
        {
          "description": "XLabs Disney",
          "enum": [
            "xlabs_disney.safetensors"
          ]
        },
        {
          "description": "XLabs MJv6",
          "enum": [
            "xlabs_mjv6.safetensors"
          ]
        },
        {
          "description": "XLabs Realism",
          "enum": [
            "xlabs_realism.safetensors"
          ]
        },
        {
          "description": "XLabs Scenery",
          "enum": [
            "xlabs_scenery.safetensors"
          ]
        },
        {
          "description": "Araminta_k Frostinglane",
          "enum": [
            "alvdansen_frostinglane_araminta_k.safetensors"
          ]
        }
      ],
      "default": "xlabs_realism.safetensors"
    },
    "lora_strength_model": {
      "type": "number",
      "widget": "select",
      "description": "Lora Strength Model",
      "oneOf": [
        {
          "description": "0",
          "enum": [
            0
          ]
        },
        {
          "description": "0.5",
          "enum": [
            0.5
          ]
        },
        {
          "description": "1",
          "enum": [
            1
          ]
        }
      ],
      "default": 1
    },
    "lora_strength_clip": {
      "type": "number",
      "widget": "select",
      "description": "Lora Strength Clip",
      "oneOf": [
        {
          "description": "0",
          "enum": [
            0
          ]
        },
        {
          "description": "0.5",
          "enum": [
            0.5
          ]
        },
        {
          "description": "1",
          "enum": [
            1
          ]
        }
      ],
      "default": 1
    },
    "sampler_name": {
      "type": "string",
      "widget": "select",
      "description": "Sampler Name",
      "oneOf": [
        {
          "description": "euler",
          "enum": [
            "euler"
          ]
        },
        {
          "description": "heun",
          "enum": [
            "heun"
          ]
        },
        {
          "description": "heunpp2",
          "enum": [
            "heunpp2"
          ]
        },
        {
          "description": "dpm_2",
          "enum": [
            "dpm_2"
          ]
        },
        {
          "description": "lms",
          "enum": [
            "lms"
          ]
        },
        {
          "description": "dpmpp_2m",
          "enum": [
            "dpmpp_2m"
          ]
        },
        {
          "description": "ipndm",
          "enum": [
            "ipndm"
          ]
        },
        {
          "description": "deis",
          "enum": [
            "deis"
          ]
        },
        {
          "description": "ddim",
          "enum": [
            "ddim"
          ]
        },
        {
          "description": "uni_pc",
          "enum": [
            "uni_pc"
          ]
        },
        {
          "description": "uni_pc_bh2",
          "enum": [
            "uni_pc_bh2"
          ]
        }
      ],
      "default": "euler"
    },
    "scheduler": {
      "type": "string",
      "widget": "select",
      "description": "Scheduler",
      "oneOf": [
        {
          "description": "normal",
          "enum": [
            "normal"
          ]
        },
        {
          "description": "sgm_uniform",
          "enum": [
            "sgm_uniform"
          ]
        },
        {
          "description": "simple",
          "enum": [
            "simple"
          ]
        },
        {
          "description": "ddim_uniform",
          "enum": [
            "ddim_uniform"
          ]
        }
      ],
      "default": "simple"
    }
  },
  "buttons": [
    {
      "id": "enter",
      "label": "ðŸ¥ª Enter"
    }
  ]
}

=== camenduru/onevision-flux.1-dev/model.json
{
    "input_image_check": "https://files.catbox.moe/yyoaah.jpg",
    "final_width": 1024,
    "tag_prompt": "Describe the image, person and text in detail, using the format of a text-to-image prompt.",
    "additional_prompt": "ultra realistic",
    "tag_seed": 0,
    "tag_temp": 0.6,
    "tag_max_tokens": 2048,
    "seed": 0,
    "steps": 20,
    "guidance": 3.5,
    "lora_file": "xlabs_realism.safetensors",
    "lora_strength_model": 1.0,
    "lora_strength_clip": 1.0,
    "sampler_name": "euler",
    "scheduler": "simple"
}
